// components/service-page/serviceIcons.js

import {
  AlertTriangle,
  Biohazard,
  Building2,
  CircleAlert,
  ClipboardCheck,
  CloudRain,
  Droplets,
  Fan,
  FileText,
  Flame,
  Hammer,
  HardHat,
  House,
  Package,
  Search,
  ShieldCheck,
  Sparkles,
  Thermometer,
  Trash2,
  TriangleAlert,
  Waves,
  Wind,
  Wrench,
} from "lucide-react";

export const serviceIcons = {
  alertTriangle: AlertTriangle,
  biohazard: Biohazard,
  building: Building2,
  circleAlert: CircleAlert,
  clipboardCheck: ClipboardCheck,
  cloudRain: CloudRain,
  droplets: Droplets,
  fan: Fan,
  fileText: FileText,
  flame: Flame,
  hammer: Hammer,
  hardHat: HardHat,
  house: House,
  package: Package,
  search: Search,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  thermometer: Thermometer,
  trash: Trash2,
  triangleAlert: TriangleAlert,
  waves: Waves,
  wind: Wind,
  wrench: Wrench,
};
